// Badge definitions - 15 starter badges across categories
// Reference: SDD-004-gamification.md

export const badgeData = [
  // STREAK BADGES
  {
    id: 'flame-keeper',
    name: 'Flame Keeper',
    description: 'Maintain a 7-day streak',
    icon: '🔥',
    category: 'streak',
    rarity: 'common',
    criteriaType: 'streak_days',
    criteriaThreshold: 7,
    isHidden: false,
    sortOrder: 1,
  },
  {
    id: 'streak-master',
    name: 'Streak Master',
    description: 'Maintain a 30-day streak',
    icon: '⚡',
    category: 'streak',
    rarity: 'rare',
    criteriaType: 'streak_days',
    criteriaThreshold: 30,
    isHidden: false,
    sortOrder: 2,
  },
  {
    id: 'legendary-streak',
    name: 'Legendary',
    description: 'Maintain a 100-day streak',
    icon: '👑',
    category: 'streak',
    rarity: 'legendary',
    criteriaType: 'streak_days',
    criteriaThreshold: 100,
    isHidden: false,
    sortOrder: 3,
  },

  // VOLUME BADGES
  {
    id: 'first-steps',
    name: 'First Steps',
    description: 'Complete your first chore',
    icon: '👣',
    category: 'volume',
    rarity: 'common',
    criteriaType: 'chores_completed',
    criteriaThreshold: 1,
    isHidden: false,
    sortOrder: 10,
  },
  {
    id: 'getting-started',
    name: 'Getting Started',
    description: 'Complete 10 chores',
    icon: '🌟',
    category: 'volume',
    rarity: 'common',
    criteriaType: 'chores_completed',
    criteriaThreshold: 10,
    isHidden: false,
    sortOrder: 11,
  },
  {
    id: 'chore-champion',
    name: 'Chore Champion',
    description: 'Complete 50 chores',
    icon: '🏆',
    category: 'volume',
    rarity: 'rare',
    criteriaType: 'chores_completed',
    criteriaThreshold: 50,
    isHidden: false,
    sortOrder: 12,
  },
  {
    id: 'century-club',
    name: 'Century Club',
    description: 'Complete 100 chores',
    icon: '💯',
    category: 'volume',
    rarity: 'epic',
    criteriaType: 'chores_completed',
    criteriaThreshold: 100,
    isHidden: false,
    sortOrder: 13,
  },

  // TIME BADGES
  {
    id: 'early-bird',
    name: 'Early Bird',
    description: 'Complete a chore before 8am',
    icon: '🐦',
    category: 'time',
    rarity: 'common',
    criteriaType: 'completion_hour_before',
    criteriaThreshold: 8,
    isHidden: false,
    sortOrder: 20,
  },
  {
    id: 'night-owl',
    name: 'Night Owl',
    description: 'Complete a chore after 8pm',
    icon: '🦉',
    category: 'time',
    rarity: 'common',
    criteriaType: 'completion_hour_after',
    criteriaThreshold: 20,
    isHidden: false,
    sortOrder: 21,
  },
  {
    id: 'weekend-warrior',
    name: 'Weekend Warrior',
    description: 'Complete chores on 5 weekends',
    icon: '⚔️',
    category: 'time',
    rarity: 'rare',
    criteriaType: 'weekend_completions',
    criteriaThreshold: 5,
    isHidden: false,
    sortOrder: 22,
  },

  // FAMILY BADGES
  {
    id: 'team-player',
    name: 'Team Player',
    description: 'Help your family reach a weekly goal',
    icon: '🤝',
    category: 'family',
    rarity: 'common',
    criteriaType: 'family_goals_reached',
    criteriaThreshold: 1,
    isHidden: false,
    sortOrder: 30,
  },
  {
    id: 'helpful-hero',
    name: 'Helpful Hero',
    description: 'Complete 10 "anyone" chores',
    icon: '🦸',
    category: 'family',
    rarity: 'rare',
    criteriaType: 'anyone_chores_completed',
    criteriaThreshold: 10,
    isHidden: false,
    sortOrder: 31,
  },
  {
    id: 'family-mvp',
    name: 'Family MVP',
    description: 'Be the weekly leader 3 times',
    icon: '⭐',
    category: 'family',
    rarity: 'epic',
    criteriaType: 'weekly_leader_count',
    criteriaThreshold: 3,
    isHidden: false,
    sortOrder: 32,
  },

  // SPECIAL BADGES
  {
    id: 'week-one',
    name: 'Week One',
    description: 'Be a ChoreChamp member for 1 week',
    icon: '📅',
    category: 'special',
    rarity: 'common',
    criteriaType: 'account_age_days',
    criteriaThreshold: 7,
    isHidden: false,
    sortOrder: 40,
  },
  {
    id: 'completionist',
    name: 'Completionist',
    description: 'Earn all other badges',
    icon: '🎯',
    category: 'special',
    rarity: 'legendary',
    criteriaType: 'all_badges_earned',
    criteriaThreshold: 14,
    isHidden: true,
    sortOrder: 99,
  },
];

export type BadgeData = (typeof badgeData)[number];
