// Character class definitions for the RPG system
// Reference: F9.1 RPG Character System

export const characterClassData = [
  {
    id: 'cleaner',
    name: 'The Cleaner',
    description: 'Masters of tidiness and deep cleaning. Cleaners excel at making spaces spotless and earn bonus XP for cleaning-related tasks.',
    icon: '🧹',
    primaryStat: 'speed',
    color: '#3B82F6', // Blue
    sortOrder: 1,
  },
  {
    id: 'organizer',
    name: 'The Organizer',
    description: 'Experts at bringing order to chaos. Organizers earn bonus XP for organizing, sorting, and decluttering tasks.',
    icon: '📦',
    primaryStat: 'quality',
    color: '#8B5CF6', // Purple
    sortOrder: 2,
  },
  {
    id: 'helper',
    name: 'The Helper',
    description: 'Always ready to lend a hand. Helpers earn bonus XP when completing shared chores and supporting family members.',
    icon: '🤝',
    primaryStat: 'teamwork',
    color: '#10B981', // Green
    sortOrder: 3,
  },
  {
    id: 'chef',
    name: 'The Chef',
    description: 'Kitchen specialists who keep the family fed. Chefs earn bonus XP for cooking, meal prep, and kitchen-related tasks.',
    icon: '👨‍🍳',
    primaryStat: 'quality',
    color: '#F59E0B', // Amber
    sortOrder: 4,
  },
  {
    id: 'guardian',
    name: 'The Guardian',
    description: 'Protectors of the home who maintain consistency. Guardians earn bonus XP for daily maintenance tasks and streak milestones.',
    icon: '🛡️',
    primaryStat: 'consistency',
    color: '#EF4444', // Red
    sortOrder: 5,
  },
];

export const characterSkillData = [
  // CLEANER SKILLS
  {
    id: 'quick-sweep',
    classId: 'cleaner',
    name: 'Quick Sweep',
    description: 'Complete cleaning tasks 10% faster',
    icon: '⚡',
    levelRequired: 1,
    effects: [{ type: 'points_bonus', value: 0.1, condition: 'category:cleaning' }],
    sortOrder: 1,
  },
  {
    id: 'deep-clean',
    classId: 'cleaner',
    name: 'Deep Clean',
    description: 'Earn 15% bonus XP for tasks marked as difficult',
    icon: '✨',
    levelRequired: 5,
    effects: [{ type: 'xp_bonus', value: 0.15, condition: 'difficulty:hard' }],
    sortOrder: 2,
  },
  {
    id: 'spotless',
    classId: 'cleaner',
    name: 'Spotless',
    description: 'Photo proof cleaning tasks earn 20% bonus points',
    icon: '📸',
    levelRequired: 10,
    effects: [{ type: 'points_bonus', value: 0.2, condition: 'has_photo:true' }],
    sortOrder: 3,
  },
  {
    id: 'cleaning-frenzy',
    classId: 'cleaner',
    name: 'Cleaning Frenzy',
    description: 'Complete 3 cleaning chores in a day for 25% XP boost on all of them',
    icon: '🌪️',
    levelRequired: 20,
    effects: [{ type: 'xp_bonus', value: 0.25, condition: 'daily_cleaning_count:3' }],
    sortOrder: 4,
  },
  {
    id: 'master-cleaner',
    classId: 'cleaner',
    name: 'Master Cleaner',
    description: 'All cleaning tasks earn double XP',
    icon: '👑',
    levelRequired: 50,
    effects: [{ type: 'xp_bonus', value: 1.0, condition: 'category:cleaning' }],
    sortOrder: 5,
  },

  // ORGANIZER SKILLS
  {
    id: 'sort-it-out',
    classId: 'organizer',
    name: 'Sort It Out',
    description: 'Organization tasks earn 10% bonus points',
    icon: '📋',
    levelRequired: 1,
    effects: [{ type: 'points_bonus', value: 0.1, condition: 'category:organization' }],
    sortOrder: 1,
  },
  {
    id: 'tidy-mind',
    classId: 'organizer',
    name: 'Tidy Mind',
    description: 'Quality stat provides 5% more bonus per point',
    icon: '🧠',
    levelRequired: 5,
    effects: [{ type: 'points_bonus', value: 0.05, condition: 'stat_multiplier:quality' }],
    sortOrder: 2,
  },
  {
    id: 'label-maker',
    classId: 'organizer',
    name: 'Label Maker',
    description: 'Earn bonus XP when completing chores with steps',
    icon: '🏷️',
    levelRequired: 10,
    effects: [{ type: 'xp_bonus', value: 0.15, condition: 'has_steps:true' }],
    sortOrder: 3,
  },
  {
    id: 'declutter-master',
    classId: 'organizer',
    name: 'Declutter Master',
    description: 'Room organization tasks earn 30% bonus XP',
    icon: '🗃️',
    levelRequired: 20,
    effects: [{ type: 'xp_bonus', value: 0.3, condition: 'tag:room_organization' }],
    sortOrder: 4,
  },
  {
    id: 'perfect-order',
    classId: 'organizer',
    name: 'Perfect Order',
    description: 'All organization tasks earn double XP',
    icon: '💎',
    levelRequired: 50,
    effects: [{ type: 'xp_bonus', value: 1.0, condition: 'category:organization' }],
    sortOrder: 5,
  },

  // HELPER SKILLS
  {
    id: 'lending-hand',
    classId: 'helper',
    name: 'Lending Hand',
    description: 'Shared chores earn 10% bonus points',
    icon: '🙌',
    levelRequired: 1,
    effects: [{ type: 'points_bonus', value: 0.1, condition: 'assignment:anyone' }],
    sortOrder: 1,
  },
  {
    id: 'team-spirit',
    classId: 'helper',
    name: 'Team Spirit',
    description: 'Family members nearby earn 5% XP when you complete chores',
    icon: '💪',
    levelRequired: 5,
    effects: [{ type: 'team_buff', value: 0.05, condition: 'nearby_family' }],
    sortOrder: 2,
  },
  {
    id: 'mentor',
    classId: 'helper',
    name: 'Mentor',
    description: 'Earn bonus XP when helping younger family members',
    icon: '📚',
    levelRequired: 10,
    effects: [{ type: 'xp_bonus', value: 0.2, condition: 'helping_younger' }],
    sortOrder: 3,
  },
  {
    id: 'family-champion',
    classId: 'helper',
    name: 'Family Champion',
    description: 'Family goals provide 25% more reward',
    icon: '🏅',
    levelRequired: 20,
    effects: [{ type: 'points_bonus', value: 0.25, condition: 'family_goal' }],
    sortOrder: 4,
  },
  {
    id: 'ultimate-helper',
    classId: 'helper',
    name: 'Ultimate Helper',
    description: 'All teamwork bonuses doubled',
    icon: '🌟',
    levelRequired: 50,
    effects: [{ type: 'team_buff', value: 1.0, condition: 'all' }],
    sortOrder: 5,
  },

  // CHEF SKILLS
  {
    id: 'sous-chef',
    classId: 'chef',
    name: 'Sous Chef',
    description: 'Kitchen tasks earn 10% bonus points',
    icon: '🔪',
    levelRequired: 1,
    effects: [{ type: 'points_bonus', value: 0.1, condition: 'category:kitchen' }],
    sortOrder: 1,
  },
  {
    id: 'meal-prep-pro',
    classId: 'chef',
    name: 'Meal Prep Pro',
    description: 'Cooking chores completed early earn 15% bonus XP',
    icon: '🥗',
    levelRequired: 5,
    effects: [{ type: 'xp_bonus', value: 0.15, condition: 'completed_early' }],
    sortOrder: 2,
  },
  {
    id: 'kitchen-king',
    classId: 'chef',
    name: 'Kitchen Ruler',
    description: 'All kitchen cleaning tasks also earn Chef XP',
    icon: '🍳',
    levelRequired: 10,
    effects: [{ type: 'xp_bonus', value: 0.2, condition: 'kitchen_cleaning' }],
    sortOrder: 3,
  },
  {
    id: 'feast-master',
    classId: 'chef',
    name: 'Feast Master',
    description: 'Complete 5 kitchen tasks in a day for massive XP bonus',
    icon: '🍽️',
    levelRequired: 20,
    effects: [{ type: 'xp_bonus', value: 0.4, condition: 'daily_kitchen_count:5' }],
    sortOrder: 4,
  },
  {
    id: 'master-chef',
    classId: 'chef',
    name: 'Master Chef',
    description: 'All kitchen tasks earn double XP',
    icon: '👨‍🍳',
    levelRequired: 50,
    effects: [{ type: 'xp_bonus', value: 1.0, condition: 'category:kitchen' }],
    sortOrder: 5,
  },

  // GUARDIAN SKILLS
  {
    id: 'watchful',
    classId: 'guardian',
    name: 'Watchful',
    description: 'Daily maintenance tasks earn 10% bonus points',
    icon: '👁️',
    levelRequired: 1,
    effects: [{ type: 'points_bonus', value: 0.1, condition: 'recurrence:daily' }],
    sortOrder: 1,
  },
  {
    id: 'streak-shield',
    classId: 'guardian',
    name: 'Streak Shield',
    description: 'Gain 1 extra streak freeze per week',
    icon: '🛡️',
    levelRequired: 5,
    effects: [{ type: 'streak_protection', value: 1, condition: 'weekly' }],
    sortOrder: 2,
  },
  {
    id: 'consistency-champion',
    classId: 'guardian',
    name: 'Consistency Champion',
    description: 'Streak milestones provide 20% more bonus',
    icon: '🔥',
    levelRequired: 10,
    effects: [{ type: 'points_bonus', value: 0.2, condition: 'streak_milestone' }],
    sortOrder: 3,
  },
  {
    id: 'iron-routine',
    classId: 'guardian',
    name: 'Iron Routine',
    description: 'Same chore completed 7 days in a row earns 30% bonus XP',
    icon: '⚙️',
    levelRequired: 20,
    effects: [{ type: 'xp_bonus', value: 0.3, condition: 'chore_streak:7' }],
    sortOrder: 4,
  },
  {
    id: 'eternal-guardian',
    classId: 'guardian',
    name: 'Eternal Guardian',
    description: 'Streak bonuses are doubled',
    icon: '🏰',
    levelRequired: 50,
    effects: [{ type: 'points_bonus', value: 1.0, condition: 'streak_bonus' }],
    sortOrder: 5,
  },
];

export type CharacterClassData = (typeof characterClassData)[number];
export type CharacterSkillData = (typeof characterSkillData)[number];
