// Mini-Game Arcade Seed Data (F9.3)

export const miniGamesSeed = [
  // Puzzle Games
  {
    id: 'clean-sweep-puzzle',
    name: 'Clean Sweep Puzzle',
    description: 'Slide tiles to reveal a sparkling clean room! Rearrange the jumbled pieces to complete the picture.',
    category: 'puzzle',
    icon: '🧩',
    thumbnail: '/games/clean-sweep-puzzle.png',
    minPlayers: 1,
    maxPlayers: 1,
    estimatedDuration: 5,
    baseXPReward: 15,
    basePointReward: 8,
    unlockType: 'default',
    unlockValue: null,
    unlockAchievementId: null,
    instructions: 'Tap adjacent tiles to slide them into the empty space. Arrange all tiles in order to complete the picture.',
    sortOrder: 1,
    isActive: true,
  },
  {
    id: 'laundry-match',
    name: 'Laundry Match',
    description: 'Match pairs of socks and clothes in this memory game! Find all matching pairs before time runs out.',
    category: 'memory',
    icon: '🧦',
    thumbnail: '/games/laundry-match.png',
    minPlayers: 1,
    maxPlayers: 4,
    estimatedDuration: 3,
    baseXPReward: 12,
    basePointReward: 6,
    unlockType: 'default',
    unlockValue: null,
    unlockAchievementId: null,
    instructions: 'Flip cards to find matching pairs. Remember the positions and match all pairs in the fewest moves!',
    sortOrder: 2,
    isActive: true,
  },
  {
    id: 'dish-stack',
    name: 'Dish Stack',
    description: 'Stack dishes perfectly in the dish rack! Balance speed and precision to get the highest score.',
    category: 'puzzle',
    icon: '🍽️',
    thumbnail: '/games/dish-stack.png',
    minPlayers: 1,
    maxPlayers: 1,
    estimatedDuration: 4,
    baseXPReward: 10,
    basePointReward: 5,
    unlockType: 'chore_count',
    unlockValue: 10,
    unlockAchievementId: null,
    instructions: 'Tap to drop dishes at the right moment. Stack them perfectly for bonus points!',
    sortOrder: 3,
    isActive: true,
  },

  // Sorting Games
  {
    id: 'recycling-rush',
    name: 'Recycling Rush',
    description: 'Sort recyclables into the correct bins! Paper, plastic, glass, and compost - can you keep up?',
    category: 'sorting',
    icon: '♻️',
    thumbnail: '/games/recycling-rush.png',
    minPlayers: 1,
    maxPlayers: 1,
    estimatedDuration: 3,
    baseXPReward: 12,
    basePointReward: 6,
    unlockType: 'default',
    unlockValue: null,
    unlockAchievementId: null,
    instructions: 'Drag items to the correct recycling bin. Sort correctly and quickly for combo bonuses!',
    sortOrder: 4,
    isActive: true,
  },
  {
    id: 'closet-organizer',
    name: 'Closet Organizer',
    description: 'Sort clothes into the right places! Shirts, pants, accessories - organize the messy closet.',
    category: 'sorting',
    icon: '👔',
    thumbnail: '/games/closet-organizer.png',
    minPlayers: 1,
    maxPlayers: 1,
    estimatedDuration: 4,
    baseXPReward: 14,
    basePointReward: 7,
    unlockType: 'chore_count',
    unlockValue: 5,
    unlockAchievementId: null,
    instructions: 'Drag clothing items to their correct locations. Keep the closet organized!',
    sortOrder: 5,
    isActive: true,
  },
  {
    id: 'grocery-sort',
    name: 'Grocery Sort',
    description: 'Put away groceries before they spoil! Fridge, pantry, freezer - sort items to their proper home.',
    category: 'sorting',
    icon: '🛒',
    thumbnail: '/games/grocery-sort.png',
    minPlayers: 1,
    maxPlayers: 1,
    estimatedDuration: 3,
    baseXPReward: 11,
    basePointReward: 5,
    unlockType: 'streak',
    unlockValue: 3,
    unlockAchievementId: null,
    instructions: 'Quickly sort groceries into the correct storage areas. Don\'t let anything spoil!',
    sortOrder: 6,
    isActive: true,
  },

  // Time Challenge Games
  {
    id: 'speed-clean',
    name: 'Speed Clean',
    description: 'Clean the room before the timer runs out! Tap dust bunnies, wipe spills, and pick up toys.',
    category: 'time-challenge',
    icon: '⚡',
    thumbnail: '/games/speed-clean.png',
    minPlayers: 1,
    maxPlayers: 1,
    estimatedDuration: 2,
    baseXPReward: 10,
    basePointReward: 5,
    unlockType: 'default',
    unlockValue: null,
    unlockAchievementId: null,
    instructions: 'Tap on messes to clean them up. Clear as many as possible before time expires!',
    sortOrder: 7,
    isActive: true,
  },
  {
    id: 'bed-making-blitz',
    name: 'Bed Making Blitz',
    description: 'Make beds as fast as you can! Sheets, blankets, pillows - perfect your bed-making skills.',
    category: 'time-challenge',
    icon: '🛏️',
    thumbnail: '/games/bed-making-blitz.png',
    minPlayers: 1,
    maxPlayers: 1,
    estimatedDuration: 2,
    baseXPReward: 10,
    basePointReward: 5,
    unlockType: 'chore_count',
    unlockValue: 15,
    unlockAchievementId: null,
    instructions: 'Follow the pattern to make the bed perfectly. Speed and accuracy both matter!',
    sortOrder: 8,
    isActive: true,
  },
  {
    id: 'dust-buster',
    name: 'Dust Buster',
    description: 'Hunt down dust bunnies hiding around the house! Find and clean them all in time.',
    category: 'time-challenge',
    icon: '🐰',
    thumbnail: '/games/dust-buster.png',
    minPlayers: 1,
    maxPlayers: 1,
    estimatedDuration: 3,
    baseXPReward: 12,
    basePointReward: 6,
    unlockType: 'level',
    unlockValue: 5,
    unlockAchievementId: null,
    instructions: 'Find and tap hidden dust bunnies. They like to hide in corners and under furniture!',
    sortOrder: 9,
    isActive: true,
  },

  // Memory Games
  {
    id: 'cleaning-supply-match',
    name: 'Cleaning Supply Match',
    description: 'Match cleaning supplies with their uses! Sponges, sprays, and more.',
    category: 'memory',
    icon: '🧴',
    thumbnail: '/games/cleaning-supply-match.png',
    minPlayers: 1,
    maxPlayers: 2,
    estimatedDuration: 4,
    baseXPReward: 13,
    basePointReward: 6,
    unlockType: 'chore_count',
    unlockValue: 20,
    unlockAchievementId: null,
    instructions: 'Match cleaning supplies with their correct uses. Test your cleaning knowledge!',
    sortOrder: 10,
    isActive: true,
  },
  {
    id: 'chore-sequence',
    name: 'Chore Sequence',
    description: 'Remember and repeat the chore sequence! The pattern gets longer each round.',
    category: 'memory',
    icon: '🔢',
    thumbnail: '/games/chore-sequence.png',
    minPlayers: 1,
    maxPlayers: 1,
    estimatedDuration: 5,
    baseXPReward: 15,
    basePointReward: 8,
    unlockType: 'streak',
    unlockValue: 7,
    unlockAchievementId: null,
    instructions: 'Watch the sequence of chores and repeat it. How long can you remember?',
    sortOrder: 11,
    isActive: true,
  },

  // Multiplayer Games
  {
    id: 'cleaning-race',
    name: 'Cleaning Race',
    description: 'Race against family members to clean the most! Compete in real-time cleaning challenges.',
    category: 'multiplayer',
    icon: '🏁',
    thumbnail: '/games/cleaning-race.png',
    minPlayers: 2,
    maxPlayers: 4,
    estimatedDuration: 5,
    baseXPReward: 20,
    basePointReward: 10,
    unlockType: 'default',
    unlockValue: null,
    unlockAchievementId: null,
    instructions: 'Race to clean the most items. The fastest cleaner wins!',
    sortOrder: 12,
    isActive: true,
  },
  {
    id: 'team-tidy',
    name: 'Team Tidy',
    description: 'Work together to clean the house! Coordinate with family members for bonus points.',
    category: 'multiplayer',
    icon: '🤝',
    thumbnail: '/games/team-tidy.png',
    minPlayers: 2,
    maxPlayers: 4,
    estimatedDuration: 8,
    baseXPReward: 25,
    basePointReward: 12,
    unlockType: 'points',
    unlockValue: 100,
    unlockAchievementId: null,
    instructions: 'Cooperate to clean different areas. Communication is key to high scores!',
    sortOrder: 13,
    isActive: true,
  },
  {
    id: 'chore-trivia',
    name: 'Chore Trivia',
    description: 'Test your household knowledge! Answer questions about chores, cleaning, and organization.',
    category: 'multiplayer',
    icon: '❓',
    thumbnail: '/games/chore-trivia.png',
    minPlayers: 2,
    maxPlayers: 6,
    estimatedDuration: 10,
    baseXPReward: 18,
    basePointReward: 9,
    unlockType: 'level',
    unlockValue: 10,
    unlockAchievementId: null,
    instructions: 'Answer trivia questions about household tasks. First to answer correctly wins the round!',
    sortOrder: 14,
    isActive: true,
  },
  {
    id: 'mess-mayhem',
    name: 'Mess Mayhem',
    description: 'Competitive cleaning chaos! Create messes for opponents while cleaning your own area.',
    category: 'multiplayer',
    icon: '💥',
    thumbnail: '/games/mess-mayhem.png',
    minPlayers: 2,
    maxPlayers: 4,
    estimatedDuration: 6,
    baseXPReward: 22,
    basePointReward: 11,
    unlockType: 'streak',
    unlockValue: 14,
    unlockAchievementId: null,
    instructions: 'Clean your area while sabotaging others. The cleanest area at the end wins!',
    sortOrder: 15,
    isActive: true,
  },
];

// Game configurations per difficulty
export const gameConfigsSeed = [
  // Clean Sweep Puzzle configs
  {
    gameId: 'clean-sweep-puzzle',
    difficulty: 'easy',
    timeLimit: 0,
    targetScore: 100,
    config: { gridSize: { rows: 3, cols: 3 }, shuffleMoves: 20 },
    xpMultiplier: 100,
    pointMultiplier: 100,
  },
  {
    gameId: 'clean-sweep-puzzle',
    difficulty: 'medium',
    timeLimit: 180,
    targetScore: 200,
    config: { gridSize: { rows: 4, cols: 4 }, shuffleMoves: 40 },
    xpMultiplier: 150,
    pointMultiplier: 150,
  },
  {
    gameId: 'clean-sweep-puzzle',
    difficulty: 'hard',
    timeLimit: 120,
    targetScore: 300,
    config: { gridSize: { rows: 5, cols: 5 }, shuffleMoves: 60 },
    xpMultiplier: 200,
    pointMultiplier: 200,
  },
  {
    gameId: 'clean-sweep-puzzle',
    difficulty: 'expert',
    timeLimit: 90,
    targetScore: 500,
    config: { gridSize: { rows: 6, cols: 6 }, shuffleMoves: 100 },
    xpMultiplier: 300,
    pointMultiplier: 300,
  },

  // Laundry Match configs
  {
    gameId: 'laundry-match',
    difficulty: 'easy',
    timeLimit: 120,
    targetScore: 100,
    config: { pairCount: 6, flipTime: 2000 },
    xpMultiplier: 100,
    pointMultiplier: 100,
  },
  {
    gameId: 'laundry-match',
    difficulty: 'medium',
    timeLimit: 90,
    targetScore: 200,
    config: { pairCount: 8, flipTime: 1500 },
    xpMultiplier: 150,
    pointMultiplier: 150,
  },
  {
    gameId: 'laundry-match',
    difficulty: 'hard',
    timeLimit: 60,
    targetScore: 300,
    config: { pairCount: 12, flipTime: 1000 },
    xpMultiplier: 200,
    pointMultiplier: 200,
  },
  {
    gameId: 'laundry-match',
    difficulty: 'expert',
    timeLimit: 45,
    targetScore: 500,
    config: { pairCount: 16, flipTime: 750 },
    xpMultiplier: 300,
    pointMultiplier: 300,
  },

  // Recycling Rush configs
  {
    gameId: 'recycling-rush',
    difficulty: 'easy',
    timeLimit: 60,
    targetScore: 100,
    config: { itemCount: 20, binCount: 3, speedMultiplier: 1.0 },
    xpMultiplier: 100,
    pointMultiplier: 100,
  },
  {
    gameId: 'recycling-rush',
    difficulty: 'medium',
    timeLimit: 60,
    targetScore: 200,
    config: { itemCount: 30, binCount: 4, speedMultiplier: 1.3 },
    xpMultiplier: 150,
    pointMultiplier: 150,
  },
  {
    gameId: 'recycling-rush',
    difficulty: 'hard',
    timeLimit: 45,
    targetScore: 300,
    config: { itemCount: 40, binCount: 5, speedMultiplier: 1.6 },
    xpMultiplier: 200,
    pointMultiplier: 200,
  },
  {
    gameId: 'recycling-rush',
    difficulty: 'expert',
    timeLimit: 30,
    targetScore: 500,
    config: { itemCount: 50, binCount: 6, speedMultiplier: 2.0 },
    xpMultiplier: 300,
    pointMultiplier: 300,
  },

  // Speed Clean configs
  {
    gameId: 'speed-clean',
    difficulty: 'easy',
    timeLimit: 60,
    targetScore: 100,
    config: { messCount: 15, spawnRate: 2000, bonusTime: 5 },
    xpMultiplier: 100,
    pointMultiplier: 100,
  },
  {
    gameId: 'speed-clean',
    difficulty: 'medium',
    timeLimit: 45,
    targetScore: 200,
    config: { messCount: 25, spawnRate: 1500, bonusTime: 3 },
    xpMultiplier: 150,
    pointMultiplier: 150,
  },
  {
    gameId: 'speed-clean',
    difficulty: 'hard',
    timeLimit: 30,
    targetScore: 300,
    config: { messCount: 35, spawnRate: 1000, bonusTime: 2 },
    xpMultiplier: 200,
    pointMultiplier: 200,
  },
  {
    gameId: 'speed-clean',
    difficulty: 'expert',
    timeLimit: 20,
    targetScore: 500,
    config: { messCount: 50, spawnRate: 750, bonusTime: 1 },
    xpMultiplier: 300,
    pointMultiplier: 300,
  },

  // Cleaning Race configs (multiplayer)
  {
    gameId: 'cleaning-race',
    difficulty: 'easy',
    timeLimit: 120,
    targetScore: 100,
    config: { itemsPerPlayer: 15, powerUpChance: 0.2 },
    xpMultiplier: 100,
    pointMultiplier: 100,
  },
  {
    gameId: 'cleaning-race',
    difficulty: 'medium',
    timeLimit: 90,
    targetScore: 200,
    config: { itemsPerPlayer: 25, powerUpChance: 0.15 },
    xpMultiplier: 150,
    pointMultiplier: 150,
  },
  {
    gameId: 'cleaning-race',
    difficulty: 'hard',
    timeLimit: 60,
    targetScore: 300,
    config: { itemsPerPlayer: 35, powerUpChance: 0.1 },
    xpMultiplier: 200,
    pointMultiplier: 200,
  },

  // Default configs for remaining games
  ...['dish-stack', 'closet-organizer', 'grocery-sort', 'bed-making-blitz',
      'dust-buster', 'cleaning-supply-match', 'chore-sequence',
      'team-tidy', 'chore-trivia', 'mess-mayhem'].flatMap(gameId => [
    {
      gameId,
      difficulty: 'easy',
      timeLimit: 120,
      targetScore: 100,
      config: { level: 1 },
      xpMultiplier: 100,
      pointMultiplier: 100,
    },
    {
      gameId,
      difficulty: 'medium',
      timeLimit: 90,
      targetScore: 200,
      config: { level: 2 },
      xpMultiplier: 150,
      pointMultiplier: 150,
    },
    {
      gameId,
      difficulty: 'hard',
      timeLimit: 60,
      targetScore: 300,
      config: { level: 3 },
      xpMultiplier: 200,
      pointMultiplier: 200,
    },
    {
      gameId,
      difficulty: 'expert',
      timeLimit: 45,
      targetScore: 500,
      config: { level: 4 },
      xpMultiplier: 300,
      pointMultiplier: 300,
    },
  ]),
];
