// Chore templates based on research: age-appropriate, 50+ templates across categories
// Reference: SDD-003-chores.md

export const choreTemplates = [
  // BEDROOM (10 templates)
  {
    title: 'Make Bed',
    description: 'Pull up sheets, arrange pillows, and smooth out the bedspread',
    icon: '🛏️',
    category: 'bedroom',
    pointValue: 5,
    difficulty: 'easy',
    estimatedMinutes: 5,
    minAge: 4,
    steps: ['Pull up flat sheet', 'Pull up comforter/blanket', 'Arrange pillows', 'Smooth out wrinkles'],
  },
  {
    title: 'Pick Up Toys',
    description: 'Put all toys back in their proper storage places',
    icon: '🧸',
    category: 'bedroom',
    pointValue: 10,
    difficulty: 'easy',
    estimatedMinutes: 10,
    minAge: 3,
    steps: ['Gather all toys from floor', 'Sort by type', 'Put in correct bins/shelves'],
  },
  {
    title: 'Put Away Clean Clothes',
    description: 'Fold and put clean laundry in drawers and closet',
    icon: '👕',
    category: 'bedroom',
    pointValue: 15,
    difficulty: 'medium',
    estimatedMinutes: 15,
    minAge: 6,
    steps: ['Sort clothes by type', 'Fold items neatly', 'Put in correct drawers', 'Hang items that need hanging'],
  },
  {
    title: 'Dust Bedroom Furniture',
    description: 'Dust all surfaces including dresser, nightstand, and shelves',
    icon: '✨',
    category: 'bedroom',
    pointValue: 15,
    difficulty: 'medium',
    estimatedMinutes: 15,
    minAge: 8,
    steps: ['Get dusting cloth', 'Dust dresser top', 'Dust nightstand', 'Dust shelves', 'Dust window sills'],
  },
  {
    title: 'Vacuum Bedroom Floor',
    description: 'Vacuum the entire bedroom floor including under furniture',
    icon: '🧹',
    category: 'bedroom',
    pointValue: 20,
    difficulty: 'medium',
    estimatedMinutes: 15,
    minAge: 10,
    steps: ['Clear floor of items', 'Plug in vacuum', 'Vacuum main area', 'Vacuum under bed', 'Vacuum corners'],
  },
  {
    title: 'Change Bed Sheets',
    description: 'Remove old sheets and put on fresh, clean ones',
    icon: '🛏️',
    category: 'bedroom',
    pointValue: 25,
    difficulty: 'hard',
    estimatedMinutes: 20,
    minAge: 10,
    steps: ['Remove pillowcases', 'Remove flat sheet', 'Remove fitted sheet', 'Put on clean fitted sheet', 'Put on clean flat sheet', 'Put on clean pillowcases'],
  },
  {
    title: 'Organize Closet',
    description: 'Organize clothes, shoes, and items in your closet',
    icon: '👔',
    category: 'bedroom',
    pointValue: 30,
    difficulty: 'hard',
    estimatedMinutes: 30,
    minAge: 10,
  },
  {
    title: 'Clean Under Bed',
    description: 'Remove items from under bed and clean the space',
    icon: '🧹',
    category: 'bedroom',
    pointValue: 20,
    difficulty: 'medium',
    estimatedMinutes: 15,
    minAge: 8,
  },
  {
    title: 'Organize Bookshelf',
    description: 'Straighten books and organize items on bookshelf',
    icon: '📚',
    category: 'bedroom',
    pointValue: 15,
    difficulty: 'medium',
    estimatedMinutes: 15,
    minAge: 7,
  },
  {
    title: 'Clean Bedroom Windows',
    description: 'Clean inside of bedroom windows',
    icon: '🪟',
    category: 'bedroom',
    pointValue: 20,
    difficulty: 'medium',
    estimatedMinutes: 15,
    minAge: 10,
  },

  // BATHROOM (8 templates)
  {
    title: 'Wipe Bathroom Counter',
    description: 'Clean and wipe down the bathroom counter and sink',
    icon: '🧽',
    category: 'bathroom',
    pointValue: 10,
    difficulty: 'easy',
    estimatedMinutes: 5,
    minAge: 6,
    steps: ['Spray counter with cleaner', 'Wipe counter', 'Wipe around sink', 'Wipe faucet'],
  },
  {
    title: 'Clean Toilet',
    description: 'Clean the toilet inside and out',
    icon: '🚽',
    category: 'bathroom',
    pointValue: 20,
    difficulty: 'medium',
    estimatedMinutes: 10,
    minAge: 10,
    steps: ['Apply toilet cleaner inside', 'Scrub with brush', 'Wipe outside with disinfectant', 'Wipe seat and lid', 'Wipe base'],
  },
  {
    title: 'Take Out Bathroom Trash',
    description: 'Empty the bathroom trash can and replace the liner',
    icon: '🗑️',
    category: 'bathroom',
    pointValue: 5,
    difficulty: 'trivial',
    estimatedMinutes: 3,
    minAge: 5,
  },
  {
    title: 'Hang Up Towels',
    description: 'Hang up towels neatly on towel rack or hooks',
    icon: '🛁',
    category: 'bathroom',
    pointValue: 5,
    difficulty: 'trivial',
    estimatedMinutes: 2,
    minAge: 4,
  },
  {
    title: 'Clean Bathroom Mirror',
    description: 'Clean and polish the bathroom mirror',
    icon: '🪞',
    category: 'bathroom',
    pointValue: 10,
    difficulty: 'easy',
    estimatedMinutes: 5,
    minAge: 7,
  },
  {
    title: 'Scrub Bathtub/Shower',
    description: 'Clean the bathtub or shower thoroughly',
    icon: '🚿',
    category: 'bathroom',
    pointValue: 25,
    difficulty: 'hard',
    estimatedMinutes: 20,
    minAge: 12,
  },
  {
    title: 'Mop Bathroom Floor',
    description: 'Mop the bathroom floor',
    icon: '🧹',
    category: 'bathroom',
    pointValue: 15,
    difficulty: 'medium',
    estimatedMinutes: 10,
    minAge: 10,
  },
  {
    title: 'Refill Soap Dispenser',
    description: 'Check and refill the soap dispenser if needed',
    icon: '🧴',
    category: 'bathroom',
    pointValue: 5,
    difficulty: 'trivial',
    estimatedMinutes: 2,
    minAge: 6,
  },

  // KITCHEN (12 templates)
  {
    title: 'Load Dishwasher',
    description: 'Load dirty dishes into the dishwasher properly',
    icon: '🍽️',
    category: 'kitchen',
    pointValue: 15,
    difficulty: 'medium',
    estimatedMinutes: 10,
    minAge: 8,
    steps: ['Rinse dishes', 'Load plates in back', 'Load bowls in back', 'Load cups on top rack', 'Add detergent'],
  },
  {
    title: 'Unload Dishwasher',
    description: 'Put away clean dishes from the dishwasher',
    icon: '🍽️',
    category: 'kitchen',
    pointValue: 15,
    difficulty: 'medium',
    estimatedMinutes: 10,
    minAge: 7,
    steps: ['Open dishwasher', 'Put away silverware', 'Put away plates', 'Put away bowls', 'Put away cups'],
  },
  {
    title: 'Wash Dishes by Hand',
    description: 'Wash dishes that cannot go in dishwasher',
    icon: '🧽',
    category: 'kitchen',
    pointValue: 20,
    difficulty: 'medium',
    estimatedMinutes: 15,
    minAge: 9,
  },
  {
    title: 'Wipe Kitchen Counters',
    description: 'Clean and wipe down all kitchen counters',
    icon: '✨',
    category: 'kitchen',
    pointValue: 10,
    difficulty: 'easy',
    estimatedMinutes: 5,
    minAge: 6,
  },
  {
    title: 'Sweep Kitchen Floor',
    description: 'Sweep the kitchen floor thoroughly',
    icon: '🧹',
    category: 'kitchen',
    pointValue: 15,
    difficulty: 'medium',
    estimatedMinutes: 10,
    minAge: 7,
  },
  {
    title: 'Set the Table',
    description: 'Set the table for a meal with plates, utensils, and napkins',
    icon: '🍴',
    category: 'kitchen',
    pointValue: 10,
    difficulty: 'easy',
    estimatedMinutes: 5,
    minAge: 5,
    steps: ['Count how many people', 'Place plates', 'Place napkins', 'Place forks and knives', 'Place cups'],
  },
  {
    title: 'Clear the Table',
    description: 'Clear dishes and clean up after a meal',
    icon: '🍽️',
    category: 'kitchen',
    pointValue: 10,
    difficulty: 'easy',
    estimatedMinutes: 5,
    minAge: 5,
  },
  {
    title: 'Take Out Kitchen Trash',
    description: 'Take out the kitchen trash and replace the bag',
    icon: '🗑️',
    category: 'kitchen',
    pointValue: 10,
    difficulty: 'easy',
    estimatedMinutes: 5,
    minAge: 8,
  },
  {
    title: 'Clean Microwave',
    description: 'Clean the inside and outside of the microwave',
    icon: '📦',
    category: 'kitchen',
    pointValue: 10,
    difficulty: 'easy',
    estimatedMinutes: 10,
    minAge: 10,
  },
  {
    title: 'Wipe Stove Top',
    description: 'Clean the stove top after cooking',
    icon: '🔥',
    category: 'kitchen',
    pointValue: 15,
    difficulty: 'medium',
    estimatedMinutes: 10,
    minAge: 12,
  },
  {
    title: 'Organize Pantry',
    description: 'Organize items in the pantry and check for expired food',
    icon: '🥫',
    category: 'kitchen',
    pointValue: 25,
    difficulty: 'hard',
    estimatedMinutes: 20,
    minAge: 10,
  },
  {
    title: 'Empty Recycling',
    description: 'Empty the recycling bin and sort recyclables',
    icon: '♻️',
    category: 'kitchen',
    pointValue: 10,
    difficulty: 'easy',
    estimatedMinutes: 5,
    minAge: 7,
  },

  // LIVING ROOM (6 templates)
  {
    title: 'Straighten Couch Cushions',
    description: 'Fluff and arrange couch cushions and pillows',
    icon: '🛋️',
    category: 'living-room',
    pointValue: 5,
    difficulty: 'trivial',
    estimatedMinutes: 3,
    minAge: 4,
  },
  {
    title: 'Dust Living Room',
    description: 'Dust all surfaces in the living room',
    icon: '✨',
    category: 'living-room',
    pointValue: 20,
    difficulty: 'medium',
    estimatedMinutes: 15,
    minAge: 8,
  },
  {
    title: 'Vacuum Living Room',
    description: 'Vacuum the living room floor and under furniture',
    icon: '🧹',
    category: 'living-room',
    pointValue: 20,
    difficulty: 'medium',
    estimatedMinutes: 15,
    minAge: 10,
  },
  {
    title: 'Pick Up Living Room',
    description: 'Put away items and tidy the living room',
    icon: '🏠',
    category: 'living-room',
    pointValue: 10,
    difficulty: 'easy',
    estimatedMinutes: 10,
    minAge: 5,
  },
  {
    title: 'Organize Remote Controls',
    description: 'Gather and organize remote controls in their spot',
    icon: '📺',
    category: 'living-room',
    pointValue: 5,
    difficulty: 'trivial',
    estimatedMinutes: 2,
    minAge: 4,
  },
  {
    title: 'Clean TV Screen',
    description: 'Carefully clean the TV screen with appropriate cleaner',
    icon: '📺',
    category: 'living-room',
    pointValue: 10,
    difficulty: 'easy',
    estimatedMinutes: 5,
    minAge: 10,
  },

  // OUTDOOR (8 templates)
  {
    title: 'Water Plants',
    description: 'Water outdoor plants and garden',
    icon: '🌱',
    category: 'outdoor',
    pointValue: 10,
    difficulty: 'easy',
    estimatedMinutes: 10,
    minAge: 5,
  },
  {
    title: 'Pull Weeds',
    description: 'Pull weeds from garden beds or lawn',
    icon: '🌿',
    category: 'outdoor',
    pointValue: 20,
    difficulty: 'medium',
    estimatedMinutes: 20,
    minAge: 8,
  },
  {
    title: 'Rake Leaves',
    description: 'Rake leaves in the yard and bag them',
    icon: '🍂',
    category: 'outdoor',
    pointValue: 25,
    difficulty: 'hard',
    estimatedMinutes: 30,
    minAge: 9,
  },
  {
    title: 'Sweep Porch/Patio',
    description: 'Sweep the porch or patio area',
    icon: '🧹',
    category: 'outdoor',
    pointValue: 15,
    difficulty: 'medium',
    estimatedMinutes: 15,
    minAge: 8,
  },
  {
    title: 'Take Out Trash Bins',
    description: 'Take trash bins to the curb on collection day',
    icon: '🗑️',
    category: 'outdoor',
    pointValue: 10,
    difficulty: 'easy',
    estimatedMinutes: 5,
    minAge: 10,
  },
  {
    title: 'Bring In Trash Bins',
    description: 'Bring trash bins back after collection',
    icon: '🗑️',
    category: 'outdoor',
    pointValue: 10,
    difficulty: 'easy',
    estimatedMinutes: 5,
    minAge: 10,
  },
  {
    title: 'Help With Yard Work',
    description: 'Help parent with various yard work tasks',
    icon: '🌳',
    category: 'outdoor',
    pointValue: 30,
    difficulty: 'hard',
    estimatedMinutes: 30,
    minAge: 10,
  },
  {
    title: 'Wash Car (Exterior)',
    description: 'Help wash the outside of the car',
    icon: '🚗',
    category: 'outdoor',
    pointValue: 30,
    difficulty: 'hard',
    estimatedMinutes: 30,
    minAge: 10,
  },

  // PETS (6 templates)
  {
    title: 'Feed Pet',
    description: 'Give your pet their daily food and fresh water',
    icon: '🐕',
    category: 'pets',
    pointValue: 10,
    difficulty: 'easy',
    estimatedMinutes: 5,
    minAge: 5,
    steps: ['Get pet food', 'Measure correct amount', 'Put in bowl', 'Refresh water bowl'],
  },
  {
    title: 'Walk Dog',
    description: 'Take the dog for a walk',
    icon: '🐕',
    category: 'pets',
    pointValue: 25,
    difficulty: 'medium',
    estimatedMinutes: 20,
    minAge: 10,
  },
  {
    title: 'Clean Litter Box',
    description: 'Scoop and clean the cat litter box',
    icon: '🐱',
    category: 'pets',
    pointValue: 15,
    difficulty: 'medium',
    estimatedMinutes: 10,
    minAge: 10,
  },
  {
    title: 'Brush Pet',
    description: 'Brush your pet\'s fur',
    icon: '🐕',
    category: 'pets',
    pointValue: 15,
    difficulty: 'medium',
    estimatedMinutes: 10,
    minAge: 7,
  },
  {
    title: 'Clean Pet Area',
    description: 'Clean the area where your pet sleeps or plays',
    icon: '🐾',
    category: 'pets',
    pointValue: 15,
    difficulty: 'medium',
    estimatedMinutes: 15,
    minAge: 8,
  },
  {
    title: 'Play With Pet',
    description: 'Spend quality playtime with your pet',
    icon: '🎾',
    category: 'pets',
    pointValue: 10,
    difficulty: 'easy',
    estimatedMinutes: 15,
    minAge: 4,
  },

  // LAUNDRY (5 templates)
  {
    title: 'Sort Laundry',
    description: 'Sort dirty laundry by color and type',
    icon: '👕',
    category: 'laundry',
    pointValue: 10,
    difficulty: 'easy',
    estimatedMinutes: 10,
    minAge: 6,
    steps: ['Separate whites', 'Separate colors', 'Separate delicates', 'Check pockets'],
  },
  {
    title: 'Load Washing Machine',
    description: 'Load clothes into the washing machine',
    icon: '🧺',
    category: 'laundry',
    pointValue: 10,
    difficulty: 'easy',
    estimatedMinutes: 5,
    minAge: 8,
  },
  {
    title: 'Move Laundry to Dryer',
    description: 'Move washed clothes from washer to dryer',
    icon: '🧺',
    category: 'laundry',
    pointValue: 10,
    difficulty: 'easy',
    estimatedMinutes: 5,
    minAge: 8,
  },
  {
    title: 'Fold Laundry',
    description: 'Fold clean laundry neatly',
    icon: '👔',
    category: 'laundry',
    pointValue: 20,
    difficulty: 'medium',
    estimatedMinutes: 20,
    minAge: 8,
  },
  {
    title: 'Put Away Family Laundry',
    description: 'Distribute folded laundry to correct rooms',
    icon: '👕',
    category: 'laundry',
    pointValue: 15,
    difficulty: 'medium',
    estimatedMinutes: 10,
    minAge: 7,
  },

  // SCHOOL (5 templates)
  {
    title: 'Pack School Bag',
    description: 'Pack backpack with needed items for school',
    icon: '🎒',
    category: 'school',
    pointValue: 10,
    difficulty: 'easy',
    estimatedMinutes: 5,
    minAge: 6,
    steps: ['Check homework is packed', 'Pack books needed', 'Pack lunch/snack', 'Check for permission slips'],
  },
  {
    title: 'Do Homework',
    description: 'Complete assigned homework',
    icon: '📚',
    category: 'school',
    pointValue: 25,
    difficulty: 'medium',
    estimatedMinutes: 30,
    minAge: 6,
  },
  {
    title: 'Read for 20 Minutes',
    description: 'Read a book for at least 20 minutes',
    icon: '📖',
    category: 'school',
    pointValue: 15,
    difficulty: 'easy',
    estimatedMinutes: 20,
    minAge: 5,
  },
  {
    title: 'Practice Instrument',
    description: 'Practice your musical instrument',
    icon: '🎵',
    category: 'school',
    pointValue: 20,
    difficulty: 'medium',
    estimatedMinutes: 20,
    minAge: 6,
  },
  {
    title: 'Organize School Supplies',
    description: 'Organize and restock school supplies',
    icon: '✏️',
    category: 'school',
    pointValue: 15,
    difficulty: 'medium',
    estimatedMinutes: 15,
    minAge: 7,
  },

  // SELF-CARE (5 templates)
  {
    title: 'Brush Teeth',
    description: 'Brush teeth for 2 full minutes',
    icon: '🪥',
    category: 'self-care',
    pointValue: 5,
    difficulty: 'trivial',
    estimatedMinutes: 2,
    minAge: 3,
    steps: ['Wet toothbrush', 'Add toothpaste', 'Brush for 2 minutes', 'Rinse mouth', 'Rinse toothbrush'],
  },
  {
    title: 'Take a Shower/Bath',
    description: 'Take a thorough shower or bath',
    icon: '🚿',
    category: 'self-care',
    pointValue: 10,
    difficulty: 'easy',
    estimatedMinutes: 15,
    minAge: 6,
  },
  {
    title: 'Get Dressed',
    description: 'Get dressed independently for the day',
    icon: '👕',
    category: 'self-care',
    pointValue: 5,
    difficulty: 'trivial',
    estimatedMinutes: 5,
    minAge: 4,
  },
  {
    title: 'Put On Pajamas',
    description: 'Change into pajamas at bedtime',
    icon: '😴',
    category: 'self-care',
    pointValue: 5,
    difficulty: 'trivial',
    estimatedMinutes: 3,
    minAge: 3,
  },
  {
    title: 'Comb/Brush Hair',
    description: 'Brush or comb your hair neatly',
    icon: '💇',
    category: 'self-care',
    pointValue: 5,
    difficulty: 'trivial',
    estimatedMinutes: 3,
    minAge: 5,
  },

  // HELPING OTHERS (5 templates)
  {
    title: 'Help Sibling with Task',
    description: 'Help a younger sibling with their chore or task',
    icon: '🤝',
    category: 'helping',
    pointValue: 20,
    difficulty: 'medium',
    estimatedMinutes: 15,
    minAge: 7,
  },
  {
    title: 'Get the Mail',
    description: 'Retrieve mail from the mailbox',
    icon: '📬',
    category: 'helping',
    pointValue: 5,
    difficulty: 'trivial',
    estimatedMinutes: 3,
    minAge: 6,
  },
  {
    title: 'Answer the Door',
    description: 'Answer the door when someone knocks (with parent permission)',
    icon: '🚪',
    category: 'helping',
    pointValue: 5,
    difficulty: 'trivial',
    estimatedMinutes: 2,
    minAge: 10,
  },
  {
    title: 'Help Carry Groceries',
    description: 'Help bring groceries inside from the car',
    icon: '🛒',
    category: 'helping',
    pointValue: 10,
    difficulty: 'easy',
    estimatedMinutes: 10,
    minAge: 6,
  },
  {
    title: 'Help Put Away Groceries',
    description: 'Help put groceries in the pantry and fridge',
    icon: '🥫',
    category: 'helping',
    pointValue: 15,
    difficulty: 'medium',
    estimatedMinutes: 10,
    minAge: 7,
  },
];

export type ChoreTemplateData = typeof choreTemplates[number];
