import type { ChoreCategory, Difficulty } from '@chorechamp/types';

export interface ChoreTemplateData {
  id: string;
  title: string;
  description: string;
  icon: string;
  category: ChoreCategory;
  pointValue: number;
  difficulty: Difficulty;
  estimatedMinutes: number;
  minAge: number | null;
  maxAge: number | null;
  steps: string[];
  tags: string[];
}

export const CHORE_TEMPLATES: ChoreTemplateData[] = [
  // Kitchen
  {
    id: 'wash-dishes',
    title: 'Wash Dishes',
    description: 'Clean all dishes in the sink',
    icon: '🍽️',
    category: 'kitchen',
    pointValue: 10,
    difficulty: 'medium',
    estimatedMinutes: 15,
    minAge: 8,
    maxAge: null,
    steps: [
      'Fill sink with warm soapy water',
      'Wash glasses first',
      'Wash plates and bowls',
      'Wash utensils',
      'Wash pots and pans',
      'Rinse everything',
      'Dry and put away',
    ],
    tags: ['daily', 'cleaning'],
  },
  {
    id: 'load-dishwasher',
    title: 'Load Dishwasher',
    description: 'Load dirty dishes into the dishwasher',
    icon: '🧽',
    category: 'kitchen',
    pointValue: 5,
    difficulty: 'easy',
    estimatedMinutes: 10,
    minAge: 6,
    maxAge: null,
    steps: [
      'Scrape food into trash',
      'Load plates on bottom rack',
      'Load cups and glasses on top',
      'Add utensils to basket',
      'Add detergent',
      'Start dishwasher',
    ],
    tags: ['daily', 'cleaning'],
  },
  {
    id: 'wipe-counters',
    title: 'Wipe Kitchen Counters',
    description: 'Clean all kitchen counter surfaces',
    icon: '✨',
    category: 'kitchen',
    pointValue: 5,
    difficulty: 'easy',
    estimatedMinutes: 5,
    minAge: 5,
    maxAge: null,
    steps: [
      'Clear items off counters',
      'Spray with cleaner',
      'Wipe with clean cloth',
      'Put items back',
    ],
    tags: ['daily', 'cleaning', 'quick'],
  },
  {
    id: 'empty-trash',
    title: 'Take Out Trash',
    description: 'Empty trash and replace bag',
    icon: '🗑️',
    category: 'kitchen',
    pointValue: 5,
    difficulty: 'easy',
    estimatedMinutes: 5,
    minAge: 7,
    maxAge: null,
    steps: [
      'Tie up trash bag',
      'Take to outdoor bin',
      'Put new bag in trash can',
    ],
    tags: ['daily', 'quick'],
  },

  // Bedroom
  {
    id: 'make-bed',
    title: 'Make Your Bed',
    description: 'Make bed neat and tidy',
    icon: '🛏️',
    category: 'bedroom',
    pointValue: 5,
    difficulty: 'easy',
    estimatedMinutes: 5,
    minAge: 4,
    maxAge: null,
    steps: [
      'Pull up sheets',
      'Straighten blanket',
      'Fluff pillows',
      'Arrange pillows nicely',
    ],
    tags: ['daily', 'quick', 'morning'],
  },
  {
    id: 'clean-room',
    title: 'Clean Your Room',
    description: 'Tidy up and organize bedroom',
    icon: '🧹',
    category: 'bedroom',
    pointValue: 15,
    difficulty: 'medium',
    estimatedMinutes: 20,
    minAge: 6,
    maxAge: null,
    steps: [
      'Pick up clothes from floor',
      'Put dirty clothes in hamper',
      'Put toys/items away',
      'Make bed',
      'Dust surfaces',
      'Vacuum or sweep floor',
    ],
    tags: ['weekly', 'cleaning'],
  },
  {
    id: 'organize-closet',
    title: 'Organize Closet',
    description: 'Organize clothes and items in closet',
    icon: '👕',
    category: 'bedroom',
    pointValue: 20,
    difficulty: 'hard',
    estimatedMinutes: 30,
    minAge: 10,
    maxAge: null,
    steps: [
      'Take everything out',
      'Sort into keep/donate piles',
      'Put keep items back neatly',
      'Bag donate items',
    ],
    tags: ['monthly', 'organization'],
  },

  // Bathroom
  {
    id: 'clean-toilet',
    title: 'Clean Toilet',
    description: 'Scrub and sanitize toilet',
    icon: '🚽',
    category: 'bathroom',
    pointValue: 10,
    difficulty: 'medium',
    estimatedMinutes: 10,
    minAge: 10,
    maxAge: null,
    steps: [
      'Apply toilet cleaner inside bowl',
      'Scrub with brush',
      'Wipe outside with disinfectant',
      'Wipe seat and lid',
      'Flush',
    ],
    tags: ['weekly', 'cleaning'],
  },
  {
    id: 'clean-sink',
    title: 'Clean Bathroom Sink',
    description: 'Clean sink and counter',
    icon: '🚿',
    category: 'bathroom',
    pointValue: 5,
    difficulty: 'easy',
    estimatedMinutes: 5,
    minAge: 7,
    maxAge: null,
    steps: [
      'Spray sink with cleaner',
      'Scrub with sponge',
      'Rinse well',
      'Wipe counter dry',
    ],
    tags: ['weekly', 'cleaning', 'quick'],
  },

  // Laundry
  {
    id: 'do-laundry',
    title: 'Do Laundry',
    description: 'Wash, dry, and fold clothes',
    icon: '🧺',
    category: 'laundry',
    pointValue: 15,
    difficulty: 'medium',
    estimatedMinutes: 15,
    minAge: 10,
    maxAge: null,
    steps: [
      'Sort clothes by color',
      'Load washing machine',
      'Add detergent',
      'Start wash cycle',
      'Move to dryer when done',
      'Fold when dry',
      'Put clothes away',
    ],
    tags: ['weekly'],
  },
  {
    id: 'fold-laundry',
    title: 'Fold Laundry',
    description: 'Fold clean clothes from dryer',
    icon: '👕',
    category: 'laundry',
    pointValue: 10,
    difficulty: 'easy',
    estimatedMinutes: 15,
    minAge: 6,
    maxAge: null,
    steps: [
      'Take clothes from dryer',
      'Fold shirts',
      'Fold pants',
      'Match and fold socks',
      'Stack by owner',
    ],
    tags: ['weekly'],
  },

  // Pet Care
  {
    id: 'feed-pet',
    title: 'Feed Pet',
    description: 'Give pet food and fresh water',
    icon: '🐕',
    category: 'pet_care',
    pointValue: 5,
    difficulty: 'easy',
    estimatedMinutes: 5,
    minAge: 5,
    maxAge: null,
    steps: [
      'Wash food bowl',
      'Add correct amount of food',
      'Refresh water bowl',
    ],
    tags: ['daily', 'quick'],
  },
  {
    id: 'walk-dog',
    title: 'Walk the Dog',
    description: 'Take dog for a walk',
    icon: '🚶',
    category: 'pet_care',
    pointValue: 15,
    difficulty: 'medium',
    estimatedMinutes: 20,
    minAge: 10,
    maxAge: null,
    steps: [
      'Get leash and bags',
      'Put on leash',
      'Walk around the block',
      'Clean up after dog',
      'Give fresh water when home',
    ],
    tags: ['daily'],
  },
  {
    id: 'clean-litter',
    title: 'Clean Litter Box',
    description: 'Scoop and clean cat litter',
    icon: '🐈',
    category: 'pet_care',
    pointValue: 10,
    difficulty: 'medium',
    estimatedMinutes: 10,
    minAge: 10,
    maxAge: null,
    steps: [
      'Get scoop and bag',
      'Scoop out waste',
      'Add fresh litter if needed',
      'Dispose of waste properly',
    ],
    tags: ['daily'],
  },

  // Outdoor
  {
    id: 'water-plants',
    title: 'Water Plants',
    description: 'Water indoor and outdoor plants',
    icon: '🌿',
    category: 'outdoor',
    pointValue: 5,
    difficulty: 'easy',
    estimatedMinutes: 10,
    minAge: 5,
    maxAge: null,
    steps: [
      'Fill watering can',
      'Check each plant',
      'Water dry plants',
      'Remove dead leaves',
    ],
    tags: ['daily', 'gardening'],
  },
  {
    id: 'rake-leaves',
    title: 'Rake Leaves',
    description: 'Rake and bag fallen leaves',
    icon: '🍂',
    category: 'outdoor',
    pointValue: 20,
    difficulty: 'hard',
    estimatedMinutes: 45,
    minAge: 10,
    maxAge: null,
    steps: [
      'Get rake and bags',
      'Rake leaves into piles',
      'Bag leaves',
      'Take bags to curb',
    ],
    tags: ['seasonal', 'fall'],
  },

  // Living Room
  {
    id: 'vacuum-living',
    title: 'Vacuum Living Room',
    description: 'Vacuum floors and rugs',
    icon: '🧹',
    category: 'living_room',
    pointValue: 10,
    difficulty: 'medium',
    estimatedMinutes: 15,
    minAge: 8,
    maxAge: null,
    steps: [
      'Pick up items from floor',
      'Move small furniture if needed',
      'Vacuum all areas',
      'Vacuum under furniture',
      'Empty vacuum if full',
    ],
    tags: ['weekly', 'cleaning'],
  },
  {
    id: 'dust-surfaces',
    title: 'Dust Surfaces',
    description: 'Dust all surfaces and shelves',
    icon: '✨',
    category: 'living_room',
    pointValue: 10,
    difficulty: 'easy',
    estimatedMinutes: 15,
    minAge: 7,
    maxAge: null,
    steps: [
      'Get duster or cloth',
      'Dust shelves',
      'Dust TV and electronics',
      'Dust picture frames',
      'Dust furniture surfaces',
    ],
    tags: ['weekly', 'cleaning'],
  },

  // General
  {
    id: 'set-table',
    title: 'Set the Table',
    description: 'Set table for meal',
    icon: '🍽️',
    category: 'general',
    pointValue: 5,
    difficulty: 'easy',
    estimatedMinutes: 5,
    minAge: 4,
    maxAge: null,
    steps: [
      'Count family members',
      'Put out plates',
      'Add utensils',
      'Set out napkins',
      'Add glasses',
    ],
    tags: ['daily', 'quick', 'mealtime'],
  },
  {
    id: 'clear-table',
    title: 'Clear the Table',
    description: 'Clear table after meal',
    icon: '🧹',
    category: 'general',
    pointValue: 5,
    difficulty: 'easy',
    estimatedMinutes: 5,
    minAge: 4,
    maxAge: null,
    steps: [
      'Stack plates carefully',
      'Gather utensils',
      'Bring dishes to kitchen',
      'Wipe table',
    ],
    tags: ['daily', 'quick', 'mealtime'],
  },
];
